// Structured detail content for each schedule day, rendered inside the day-detail modal.
// Block types: p (paragraph), h (subheading), list (bullets), flow (arrow-chained steps),
// price (pricing grid), note (small italic note), contact (contact line), footer (bold closing line).

export const DAY_DETAILS = {
    'Day 1': [
        { type: 'p', lead: true, text: 'The perfect opening to three days of fitness, competition & energy.' },
        { type: 'p', text: 'Day 1 kicks off NPC Regionals Chandigarh 2026 with the Tri-Rox Challenge by Tripat Singh — a high-intensity fitness experience built around running, strength, power and endurance.' },
        { type: 'p', text: 'Athletes will push through a series of challenging fitness stations, with every movement followed by a run, testing not just strength but speed, conditioning and mental toughness.' },
        { type: 'h', text: 'What to Expect' },
        { type: 'flow', items: ['Sandbag Lunges → Run', 'Trap-Bar Farmers Walk → Run', 'Tyre Flip → Run', 'Box Jumps → Run', 'Burpees → Run', 'Floor-to-Overhead Press → Run to Finish'] },
        { type: 'h', text: 'Choose Your Challenge' },
        { type: 'p', text: 'Tri-Rox is designed for different levels of participation:' },
        { type: 'list', items: ['Competitive — Men & Women', 'Non-Competitive'] },
        { type: 'note', text: 'Rule Book will be shared upon registration and will be available on our social media platforms as well.' },
        { type: 'price', items: [{ label: 'Competitive', price: '₹2,000' }, { label: 'Non-Competitive', price: '₹1,500' }] },
        { type: 'h', text: "And It's Not Just for Athletes!" },
        { type: 'p', text: 'Day 1 will also bring a range of fun fitness challenges and interactive games for visitors and fitness enthusiasts. Expect challenges like:' },
        { type: 'list', items: ['🔥 Clock Push-Up Challenge', '💪 Dead Hang Challenge', '❤️ Couple Fun Games', 'And more surprise fitness activities throughout the day'] },
        { type: 'p', text: "Whether you're stepping onto the competition floor or cheering from the sidelines, Day 1 is built to get everyone moving." },
        { type: 'p', bold: true, text: 'Come compete. Come challenge yourself. Come experience the energy.' },
        { type: 'footer', text: '9 October | NPC Regionals Chandigarh 2026 | Panchkula' },
        { type: 'contact', text: 'For More Info contact: 6284704810' },
    ],
    'Day 2': [
        { type: 'p', lead: true, text: 'A full day of strength, power and performance.' },
        { type: 'p', text: 'Day 2 turns up the intensity with two major strength-driven experiences — the Tri-Rox Challenge continues, followed by the Indian Powerlifting League, bringing some of the strongest athletes together under one roof.' },
        { type: 'h', text: 'Tri-Rox Challenge — Day 2' },
        { type: 'p', text: 'The Tri-Rox action continues with athletes taking on a demanding combination of running, strength and functional fitness. Every station is a test of pace, power and endurance — and every second counts.' },
        { type: 'p', bold: true, text: 'Competitive & Non-Competitive | Men & Women' },
        { type: 'p', text: "Whether you're chasing the leaderboard or simply testing your limits, Tri-Rox is built to push you beyond your comfort zone." },
        { type: 'h', text: 'Indian Powerlifting League' },
        { type: 'p', text: 'The second half of Day 2 belongs to pure strength.' },
        { type: 'p', text: 'Conducted by renowned powerlifting personality Bhupinder Dhawan, the Indian Powerlifting League brings the classic strength disciplines to the stage:' },
        { type: 'list', items: ['Squat', 'Bench Press', 'Deadlift', 'Multiple Weight Categories'] },
        { type: 'p', text: 'From the first lift to the final deadlift, expect an atmosphere charged with strength, precision and competition.' },
        { type: 'h', text: 'Participation Options' },
        { type: 'price', items: [{ label: 'Single', price: '₹1,500' }, { label: 'Double', price: '₹2,000' }, { label: 'Triple', price: '₹2,500' }] },
        { type: 'p', text: 'With athletes competing, influencers and fitness personalities around, an expo buzzing with activity and interactive fitness challenges for visitors, Day 2 is where strength takes centre stage.' },
        { type: 'p', bold: true, text: 'Two competitions. One massive day. Pure strength & performance.' },
        { type: 'footer', text: '10 October | NPC Regionals Chandigarh 2026 | Panchkula' },
    ],
    'Day 3': [
        { type: 'p', lead: true, text: 'The stage where physique, discipline and years of hard work come together.' },
        { type: 'p', text: 'The grand finale of NPC Regionals Chandigarh 2026 belongs to bodybuilding and physique athletes. Day 3 brings competitors from across the country to the stage for a premium championship experience judged by national-level judges.' },
        { type: 'p', text: 'This is where preparation meets presentation — muscularity, symmetry, conditioning, proportions and stage presence all come together to determine who stands above the rest.' },
        { type: 'h', text: 'Step on the Stage' },
        { type: 'p', text: 'The championship will feature multiple bodybuilding and physique categories, giving athletes the opportunity to compete at a national-level platform and showcase the results of their dedication.' },
        { type: 'h', text: 'Road to Sheru Classic' },
        { type: 'p', text: "This isn't just another competition. The event is associated with Sheru Classic and carries the #RoadToSheruClassic positioning, giving participating athletes the opportunity to pursue the next level of competitive bodybuilding, with the pathway leading toward the Sheru Classic stage in Delhi or Mumbai." },
        { type: 'h', text: 'Compete Your Way' },
        { type: 'price', items: [{ label: 'Single Entry', price: '₹3,500' }, { label: 'Double Entry', price: '₹6,000' }, { label: 'Triple Entry', price: '₹8,500' }] },
        { type: 'note', text: 'Tanning facility: Available at ₹2,000 per athlete.' },
        { type: 'h', text: 'The Grand Finale' },
        { type: 'p', text: 'Expect a day filled with elite physiques, national-level judging, athletes, influencers, fitness enthusiasts and an electrifying audience as the three-day festival reaches its climax.' },
        { type: 'p', text: "Whether you're an athlete stepping under the lights, a coach supporting your competitor, or a fan of bodybuilding and physique sports — Day 3 is where the spotlight belongs to the athletes." },
        { type: 'p', bold: true, text: 'The Stage Is Set. The Physiques Are Ready.' },
        { type: 'footer', text: '11 October | NPC Regionals Chandigarh 2026 | Panchkula · #RoadToSheruClassic' },
    ],
};
